In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [17]:
import keras


ModuleNotFoundError: No module named 'tensorflow.compat'

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6933, 1782, 9538, 7060],
 [6933, 1782, 9538, 4375],
 [6933, 7025, 9538, 4994],
 [2067, 7299, 1502, 9008, 3863],
 [2067, 7299, 1502, 9008, 5967],
 [896, 6933, 8615, 9538, 2680],
 [8332, 7627, 1622, 9008]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6933 1782 9538 7060]
 [   0    0    0    0 6933 1782 9538 4375]
 [   0    0    0    0 6933 7025 9538 4994]
 [   0    0    0 2067 7299 1502 9008 3863]
 [   0    0    0 2067 7299 1502 9008 5967]
 [   0    0    0  896 6933 8615 9538 2680]
 [   0    0    0    0 8332 7627 1622 9008]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 132ms/step


array([[[-0.03167697, -0.01129351,  0.01975479, -0.0387794 ,
         -0.01568038,  0.02628534,  0.00924586,  0.03356769,
          0.02589274, -0.0309998 ],
        [-0.03167697, -0.01129351,  0.01975479, -0.0387794 ,
         -0.01568038,  0.02628534,  0.00924586,  0.03356769,
          0.02589274, -0.0309998 ],
        [-0.03167697, -0.01129351,  0.01975479, -0.0387794 ,
         -0.01568038,  0.02628534,  0.00924586,  0.03356769,
          0.02589274, -0.0309998 ],
        [-0.03167697, -0.01129351,  0.01975479, -0.0387794 ,
         -0.01568038,  0.02628534,  0.00924586,  0.03356769,
          0.02589274, -0.0309998 ],
        [ 0.02947653,  0.02852466,  0.02064506, -0.00574272,
          0.04779477, -0.04508482, -0.0359484 , -0.03446455,
          0.04430174, -0.01418214],
        [ 0.04513296, -0.00621722,  0.00513292, -0.04443559,
         -0.04414323,  0.00077445, -0.00539219,  0.04589731,
         -0.00551224, -0.03545781],
        [ 0.01732167,  0.01659891, -0.03761937, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531